os: osx
addons:
  homebrew:
    packages:
      - git
      - pkgconfig
      - automake
      - autoconf
      - libtool
      - coreutils
      - python3

install:
  - sudo easy_install pip3
  - sudo pip3 install pyblake2 pyzmq pyflakes simplejson
script:
  - make -C ./depends
  - ./zcutil/build.sh -j2
  - ./zcutil/fetch-params.sh

jobs:
  include:
    - stage: test
      script: ./qa/zcash/full_test_suite.py $TEST_TARGET
      env:
      - TEST_TARGET=rpc
    - script: ./qa/zcash/full_test_suite.py $TEST_TARGET
      name: "btest"
      env:
      - TEST_TARGET=btest
    # - # stage name not required, will continue to use `test`
    #   script: ./qa/zcash/full_test_suite.py $TEST_TARGET
    #   env:
    #   -TEST_TARGET=sec-hard
    # - # stage name not required, will continue to use `test`
    #   script: ./qa/zcash/full_test_suite.py $TEST_TARGET
    #   env:
    #   - TEST_TARGET=no-dot-so
    # - # stage name not required, will continue to use `test`
    #   script: ./qa/zcash/full_test_suite.py $TEST_TARGET
    #   env:
    #   - TEST_TARGET=util-test
    # - # stage name not required, will continue to use `test`
    #   script: ./qa/zcash/full_test_suite.py $TEST_TARGET
    #   env:
    #   - TEST_TARGET=secp256k1
    # - # stage name not required, will continue to use `test`
    #   script: ./qa/zcash/full_test_suite.py $TEST_TARGET
    #   env:
    #   - TEST_TARGET=univalue
    # - # stage name not required, will continue to use `test`
    #   script: ./qa/zcash/full_test_suite.py $TEST_TARGET
    #   env:
    #   - TEST_TARGET=secp256k1
    # - # stage name not required, will continue to use `test`
    #   script: ./qa/zcash/full_test_suite.py $TEST_TARGET
    #   env:
    #   - TEST_TARGET=rust-test
    # - # stage name not required, will continue to use `test`
    #   script: ./qa/zcash/full_test_suite.py $TEST_TARGET
    #   env:
    #   - TEST_TARGET=rpc
    # - stage: lint
    #   script: pyflakes $LINT_TARGET
    #   env:
    #   - LINT_TARGET=qa
    # - # stage name not required, will continue to use `lint`
    #   script: pyflakes $LINT_TARGET
    #   env:
    #   - LINT_TARGET=src
    # - # stage name not required, will continue to use `lint`
    #   script: pyflakes $LINT_TARGET
    #   env:
    #   - LINT_TARGET=zcutil

#jobs:
#  include:
#    - stage: 
#after_success:
#  - ./zcutil/fetch-params.sh
#  - ./qa/zcash/full_test_suite.py $TEST_TARGET
#  - pyflakes $LINT_TARGET

