os: osx
addons:
  homebrew:
    packages:
      - git
      - pkgconfig
      - automake
      - autoconf
      - libtool
      - coreutils
env:
  - TEST_TARGET=btest
  - TEST_TARGET=gtest
  - TEST_TARGET=sec-hard
  - TEST_TARGET=not-dot-so
  - TEST_TARGET=util-test
  - TEST_TARGET=secp256k1
  - TEST_TARGET=univalue
  - TEST_TARGET=rust-test
  - TEST_TARGET=rpc
install:
  - sudo easy_install pip
  - sudo pip install pyblake2 pyzmq simplejson
script:
  - make -C ./depends
  - ./zcutil/build.sh -j2
after_success:
  - ./zcutil/fetch-params.sh
  - ./qa/zcash/full_test_suite.py $TEST_TARGET
  - ./qa/zcash/full_test_suite.py $TEST_TARGET
  - ./qa/zcash/full_test_suite.py $TEST_TARGET
  - ./qa/zcash/full_test_suite.py $TEST_TARGET
  - ./qa/zcash/full_test_suite.py $TEST_TARGET
  - ./qa/zcash/full_test_suite.py $TEST_TARGET
  - ./qa/zcash/full_test_suite.py $TEST_TARGET
  - ./qa/zcash/full_test_suite.py $TEST_TARGET
  - ./qa/zcash/full_test_suite.py $TEST_TARGET
  - pyflakes qa src zcutil
